### ISSUE TITLE
Elite Crafting Table Recipe

### ISSUE THREAD

**Issue by enrymax00** [EvergoodTeam/Evergood#2]
crafting issue: i can't craft nasa workbench, i need blue gem for elite crafting table but i can't'make the rocket

**Comment by Librv** [comment]
Already aware, quite a stupid mistake on my part if I have to be honest, I'll upload a dev build in a bit with the fix and some changes.
I'll close the issue once it is available, thanks for reporting it!

**Comment by Librv** [comment]
[This should fix up the issues](https://github.com/EvergoodTeam/Evergood/releases/tag/v0.2.96-dev1)

If you find any other problem or if the current issue reappears, please report it. Thank you.
