### ISSUE TITLE
OTGCore incorrect version

### ISSUE THREAD

**Issue by JoshyKulcu** [EvergoodTeam/Evergood#3]
Hi, after the recent update I have been unable to load into the game as it says OTGCore isn't the correct version, please fix this asap

**Comment by Librv** [comment]
Open the mods folder, go into the 1.12.2 folder and delete the OTG Core jar file
That should fix your problem

**Comment by JoshyKulcu** [comment]
Wow, yeah that worked thank you, thanks for the very fast reply as well, I really appreciate it, great pack btw.

**Comment by Librv** [comment]
Thank you! Really means a lot, happy holidays!
